spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shopping_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
        password: ${DEFAULT_PASS:roni95}

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    mvc:
        hiddenmethod:
            filter:
                enabled: true
    sql:
        init:
            mode: never
    #      should be always on first start

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect

        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true

    data:
        web:
            pageable:
                one-indexed-parameters: true

    #Cloudinary Properties cloud
    #cloudinary:
    #api-key:
    #api-secret:
    #cloud-name:


logging:
    level:
        org.springframework.security: TRACE

server:
    port: 8000

#    error:
##        include-exception: true
##        include-stacktrace: always
#        whitelabel:
#          enabled: off


mail:
    host: localhost
    port: 1025
    username: "admin@ShopLizt.com"
    password: ""